import { AiSettingsPanel } from '@/components/settings/AiSettingsPanel';
import type { AiSettings } from '@/lib/ai/settings';
import type { GameState, QuestStatus } from '@/lib/game/types';

const questStatusLabel: Record<QuestStatus, string> = { active: 'aktiv', completed: 'abgeschlossen', failed: 'gescheitert' };

export function SidePanel({ game, aiSettings, onAiSettingsChange, onSave, onNew, onDelete }: { game: GameState; aiSettings: AiSettings; onAiSettingsChange: (settings: AiSettings) => void; onSave: () => void; onNew: () => void; onDelete: () => void }) {
  const visibleQuests = game.quests.filter((quest) => quest.status === 'active' || quest.status === 'completed' || quest.status === 'failed');
  const health = typeof game.status.health === 'number' ? Math.max(0, Math.min(100, game.status.health)) : 100;
  const moodOrDanger = game.status.dangerLevel ?? game.status.mood;
  return <aside className="side-panel"><h2>{game.name}</h2><div className="panel-actions"><button onClick={onSave}>Spiel speichern</button><button onClick={onNew}>Neues Spiel</button><button onClick={onDelete}>Spielstand löschen</button></div><AiSettingsPanel settings={aiSettings} onChange={onAiSettingsChange} /><section className="status-card"><h3>Spielstatus</h3><p><strong>Ort:</strong> {String(game.status.location ?? 'Unbekannt')}</p><div className="health-row"><span>Lebenspunkte</span><strong>{health}/100</strong></div><div className="health-bar"><span style={{ width: `${health}%` }} /></div>{moodOrDanger ? <p><strong>{game.status.dangerLevel ? 'Gefahr' : 'Stimmung'}:</strong> {String(moodOrDanger)}</p> : null}</section><section><h3>Quests</h3>{visibleQuests.length ? <ul className="quest-list">{visibleQuests.map((quest) => <li className={`quest-card ${quest.status}`} key={quest.id}><div><strong>{quest.title}</strong><span>{questStatusLabel[quest.status]}</span></div><p>{quest.description || 'Keine Beschreibung vorhanden.'}</p>{quest.objectives.map((objective) => { const percent = Math.min(100, Math.round((objective.progress / objective.target) * 100)); return <div className="objective" key={objective.id}><small>{objective.completed ? '✓ erfüllt' : '• offen'} · {objective.title} ({objective.progress}/{objective.target})</small><div className="objective-bar"><span style={{ width: `${percent}%` }} /></div></div>; })}</li>)}</ul> : <p className="empty-state">Noch keine Quests. Die erste Aufgabe wartet darauf, entdeckt zu werden.</p>}</section><section><h3>Inventar</h3>{game.inventory.length ? <ul className="inventory-list">{game.inventory.map((item) => <li key={item.id} title={item.name}><span>{item.name}</span><strong>× {item.quantity}</strong><small>{item.category}</small></li>)}</ul> : <p className="empty-state">Dein Rucksack ist noch leer.</p>}</section></aside>;
}
